name: build

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md
      - LICENSE

  workflow_dispatch:

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        id: gradle-build
        run: |
          ./gradlew build --warning-mode all
