name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - LICENSE

  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md
      - LICENSE

env:
  enable_build: true
  enable_androidLint: true
  enable_ktlint: false

jobs:
  build:
    runs-on: ubuntu-latest
    if: $enable_build == 'true'
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDebug 2>&1 | tee build.log
        continue-on-error: true

      - name: Upload build.log
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build.log

      - name: Setup Ruby, JRuby and TruffleRuby
        if: github.event_name == 'pull_request'
        uses: ruby/setup-ruby@v1.171.0
        with:
          ruby-version: '3.3'

      - uses: actions/cache@v4
        if: github.event_name == 'pull_request'
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - uses: MeilCli/danger-action@v5
        if: github.event_name == 'pull_request'
        with:
          plugins_file: 'ci/build/Gemfile'
          install_path: 'vendor/bundle'
          danger_file: 'ci/build/Dangerfile'
          danger_id: 'danger-pr-build'
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  androidLint:
    runs-on: ubuntu-latest
    #if: ${{ env.ENABLE_ANDROID_LINT }} == true
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Inspection
        run: ./gradlew lint

      - name: Upload androidLint reports
        uses: actions/upload-artifact@v4
        with:
          name: androidLint-reports
          path: |
            app/build/reports/lint-results-*.html
            app/build/reports/lint-results-*.xml

      - name: Setup Ruby, JRuby and TruffleRuby
        if: github.event_name == 'pull_request'
        uses: ruby/setup-ruby@v1.171.0
        with:
          ruby-version: '3.3'

      - uses: actions/cache@v4
        if: github.event_name == 'pull_request'
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - uses: MeilCli/danger-action@v5
        if: github.event_name == 'pull_request'
        with:
          plugins_file: 'ci/androidLint/Gemfile'
          install_path: 'vendor/bundle'
          danger_file: 'ci/androidLint/Dangerfile'
          danger_id: 'danger-pr-androidLint'
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ktlint:
    runs-on: ubuntu-latest
    #if: ${{ env.ENABLE_KTLINT }} == true
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Inspection
        run: ./gradlew lintKotlin

      - name: Upload ktlint reports
        uses: actions/upload-artifact@v4
        with:
          name: ktlint-reports
          path: |
            app/build/reports/ktlint/*

      - name: Setup Ruby, JRuby and TruffleRuby
        if: github.event_name == 'pull_request'
        uses: ruby/setup-ruby@v1.171.0
        with:
          ruby-version: '3.3'

      - uses: actions/cache@v4
        if: github.event_name == 'pull_request'
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - uses: MeilCli/danger-action@v5
        if: github.event_name == 'pull_request'
        with:
          plugins_file: 'ci/ktlint/Gemfile'
          install_path: 'vendor/bundle'
          danger_file: 'ci/ktlint/Dangerfile'
          danger_id: 'danger-pr-ktlint'
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
